server:
  port: 8090   
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MySample
    username: root
    password: Amit@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        current_session_context_class: thread
        format_sql: true
        jdbc:

          lob:
            non_contextual_creation: true
